### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by jolespin** [dmuellner/fastcluster#10]
```
(custom_env) -bash-4.1$ pip install fastcluster
Requirement already satisfied: fastcluster in /usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/custom_env/lib/python3.6/site-packages (1.1.25)
Requirement already satisfied: numpy>=1.9 in /usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/custom_env/lib/python3.6/site-packages (from fastcluster) (1.13.3)
(custom_env) -bash-4.1$ python
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastcluster
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda/envs/custom_env/lib/python3.6/site-packages/fastcluster.py", line 37, in <module>
    from _fastcluster import linkage_wrap, linkage_vector_wrap
ImportError: numpy.core.multiarray failed to import
```

**Comment by dmuellner** [comment]
Solution 1: Can you update NumPy on your machine? (`pip install numpy`)

Solution 2: Can you download and install fastcluster from source?
```
pip uninstall fastcluster
wget https://files.pythonhosted.org/packages/ff/f4/20a1578c09236272e16e650afd53841bd86dd57fea0f15e6d3a5e66f14be/fastcluster-1.1.25.tar.gz
tar -xvf fastcluster-1.1.25.tar.gz 
cd fastcluster-1.1.25
python3 setup.py install --user
```
(You may leave out the last `--user` flag.)

**Comment by jolespin** [comment]
Is there a Numpy that is preferred for fastcluster?

**Comment by dmuellner** [comment]
No, any recent NumPy version should work.

**Comment by leonard-seydoux** [comment]
Same issue here. Did you find a solution meanwhile?
I am using the `numpy` version (`1.20.2`) with Python 3.7.5, and fastcluster version 1.2.3.
