### ISSUE TITLE
Fresh install on python 3.9 fails, numpy is installed on machine

### ISSUE THREAD

**Issue by vshesh** [dmuellner/fastcluster#17]
Unclear why `pip3 install fastcluster` worked perfectly fine on python 3.8, but fails on python 3.9: 

Platform: Mac OS X 10.13

```python
$ pip3 list | grep numpy
numpy            1.19.4
$ pip3.8 install fastcluster
Collecting fastcluster
  Using cached fastcluster-1.1.26.tar.gz (168 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied, skipping upgrade: numpy>=1.9 in /usr/local/lib/python3.8/site-packages (from fastcluster) (1.19.2)
Building wheels for collected packages: fastcluster
  Building wheel for fastcluster (PEP 517) ... done
  Created wheel for fastcluster: filename=fastcluster-1.1.26-cp38-cp38-macosx_10_13_x86_64.whl size=37698 sha256=0d2dc0fc46e584f8382a6c4c7aa144894c7ace04b4384e5bc4036da3a35d89f2
  Stored in directory: /Users/Vishesh/Library/Caches/pip/wheels/4a/84/ed/b44fced080be520d0736624dfc5a2cbbc4122bd7935d88a774
Successfully built fastcluster
Installing collected packages: fastcluster
Successfully installed fastcluster-1.1.26
$ pip3 install fastcluster # pip3 -> pip3.9
Collecting fastcluster
  Using cached fastcluster-1.1.26.tar.gz (168 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/tmpeshy94lh
       cwd: /private/var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/pip-install-pu5wgjd8/fastcluster
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/pip-build-env-h_w5np5s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/pip-build-env-h_w5np5s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/pip-build-env-h_w5np5s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/pip-build-env-h_w5np5s/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 12, in <module>
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/ks/l4yg1dsn4tn60jznwm0nc44w0000gn/T/tmpeshy94lh Check the logs for full command output.
```

**Comment by cdiener** [comment]
Same for me but I get the following error:

```
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpp5ojf0zv_in_process.py get_requires_for_build_wheel /tmp/tmpsfrah6jw
       cwd: /tmp/pip-install-dsrazb_u/fastcluster
  Complete output (19 lines):
  Version: 1.1.26
  Traceback (most recent call last):
    File "/tmp/tmpp5ojf0zv_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpp5ojf0zv_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpp5ojf0zv_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ss4kb5ie/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-ss4kb5ie/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ss4kb5ie/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-ss4kb5ie/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 84, in <module>
      include_dirs=[numpy.get_include()],
  AttributeError: module 'numpy' has no attribute 'get_include'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpp5ojf0zv_in_process.py get_requires_for_build_wheel /tmp/tmpsfrah6jw Check the logs for full command output.
```

**Comment by mrswats** [comment]
I am having the same error. Easily reproducible with docker:
```
$ docker run --rm -it python:latest bash
root@cc5425490179:/# pip install fastcluster
Collecting fastcluster
  Downloading fastcluster-1.1.26.tar.gz (168 kB)
     |████████████████████████████████| 168 kB 3.2 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpomrltud8
       cwd: /tmp/pip-install-17w3t4zd/fastcluster_857b7a1b65064b758bd221fb65450920
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-ldfxcmq9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-ldfxcmq9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-ldfxcmq9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-ldfxcmq9/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 12, in <module>
      import numpy
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpomrltud8 Check the logs for full command output.
root@cc5425490179:/#
```

**Comment by dmuellner** [comment]
Please use the option `--no-use-pep517`. The following command works on my machine:
```
 pip install --user --no-use-pep517 fastcluster
```
So far, I don't know what this option does and will investigate how to get rid of this flag.

**Comment by mrswats** [comment]
@dmuellner That's okay if ytou are only installing fastcluster on its own. However, in my project it is installed as another dependency so I do not have this option.

I believe this might be the new resolver at play that resolves dependencies to make sure everything is consistent.

**Comment by dmuellner** [comment]
Now I understand the problem. The `pyproject.toml` in fastcluster-1.1.26 does not have an entry for the NumPy dependency for Python 3.9. (The Github version has.)

I might need to make a new release just for this. If anyone has a better idea (sneaking an updated `pyproject.toml` into an existing release), let me know.

**Comment by mrswats** [comment]
I don't think there's nothing wrong with a new release. I think that's the "proper" way of doing it anyway. New version of python, new version of the library. All good.

**Comment by dmuellner** [comment]
I made a new release: 1.1.27.
