### ISSUE TITLE
 test_vector (tests.fastcluster_test) fails with ERROR

### ISSUE THREAD

**Issue by mcepl** [dmuellner/fastcluster#21]
When running the test suite while packaging the latest release fastcluster 1.1.28 for openSUSE, I get one tests erroring (both with Python 3.8 and 3.9):
```
[   28s] + python3.9 -m unittest -v tests
[   34s] test (tests.fastcluster_test) ... ok
[   34s] test_nan (tests.fastcluster_test) ... ok
[   35s] test_vector (tests.fastcluster_test) ... ERROR
[   35s]
[   35s] ======================================================================
[   35s] ERROR: test_vector (tests.fastcluster_test)
[   35s] ----------------------------------------------------------------------
[   35s] Traceback (most recent call last):
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/tests/vectortest.py", line 68, in test_all
[   35s]     Z2 = fc.linkage_vector(pcd, method, metric)
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/fastcluster.py", line 492, in linkage_vector
[   35s]     linkage_vector_wrap(X, Z, mthidx[method], mtridx[metric], extraarg)
[   35s] FloatingPointError: NaN dissimilarity value.
[   35s]
[   35s] During handling of the above exception, another exception occurred:
[   35s]
[   35s] Traceback (most recent call last):
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/tests/vectortest.py", line 237, in test
[   35s]     test_all(n,dim)
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/tests/vectortest.py", line 76, in test_all
[   35s]     raise AssertionError('"linkage_vector" erroneously reported NaN.')
[   35s] AssertionError: "linkage_vector" erroneously reported NaN.
[   35s]
[   35s] During handling of the above exception, another exception occurred:
[   35s]
[   35s] Traceback (most recent call last):
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/tests/__init__.py", line 14, in test_vector
[   35s]     self.assertTrue(test(10))
[   35s]   File "/home/abuild/rpmbuild/BUILD/fastcluster-1.1.28/tests/vectortest.py", line 240, in test
[   35s]     print(E.args[1])
[   35s] IndexError: tuple index out of range
[   35s]
[   35s] ----------------------------------------------------------------------
[   35s] Ran 3 tests in 6.709s
[   35s]
[   35s] FAILED (errors=1)
```
[Complete build log](https://github.com/dmuellner/fastcluster/files/6526307/_log.txt) with all details of packages used and steps run.

**Comment by dmuellner** [comment]
The definition of the Yule metric in SciPy changed slightly in https://github.com/scipy/scipy/commit/3b22d1da98dc1b5f64bc944c21f398d4ba782bce. I will adapt the fastcluster library.

**Comment by dmuellner** [comment]
Fixed in the new fastcluster version 1.2.0.

**Comment by mcepl** [comment]
Thank you, works perfectly.

**Comment by mcepl** [comment]
Err, actually. Would it be possible to make the change slightly more tolerant? We have scipy 1.5.4 in older distributions of openSUSE, should we just give up on the latest version of fastcluster or would it be possible to introduce some kind of test to check what scipy requires?

**Comment by dmuellner** [comment]
The best way would indeed be to install fastcluster 1.1.x along with SciPy <1.6.3 and fastcluster 1.2.x with SciPy >=1.6.3. Is that something you can do? I am wary of relaxing the unit tests since this would introduce inconsistent results bewteen SciPy and fastcluster in mixed installations.

I should maybe clarify in the documentation that fastcluster 1.1.x is working fine and recommended for older SciPy versions.
